### ISSUE TITLE
led indicators on branch 'led_indicator'

### ISSUE THREAD

**Issue by Glitch-guy0** [Glitch-guy0/Parking_Slot_Reporter#4]
which has 4 slot(1-4) indicators and 1 master(0)

master: turns red when all 4 slot indicators are red

slot: turns red when ir_sensor.near of that slot is true

**Comment by Sunilkumar01111** [comment]
I will work on this

**Comment by Glitch-guy0** [comment]
commit of code on behalf of @Sunilkumar01111 

# todo 
- [ ] have to checkout pins used for this project with servo project
